name: revani
description: "A new Flutter package project."
version: 1.0.0
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.7
  encrypt: ^5.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

