name: revani
description: Ultra-Fast, Ultra-Secure, Actor-Model Based Modern NoSQL Database SDK.
version: 3.1.0
repository: https://github.com/JeaFrid/revani_dart_sdk
homepage: https://github.com/JeaFrid/revani_dart_sdk

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.7
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

